import type { Localized } from '../types';

export const englishDigitalSignageContent = {
  seo: { title: 'NeoSlide Digital Signage | BlackBox Solutions', description: 'Turn any screen into a managed digital signage display with NeoSlide. Create, schedule, and publish content from one cloud dashboard.' },
  hero: { ariaLabel: 'Digital signage hero', headlineStart: 'Turn any screen into a powerful ', highlights: ['digital', 'signage', 'display.'], lead: 'Manage all your digital displays from one cloud-based platform. Create, schedule, and publish content in minutes, then update every screen remotely with just a few clicks.', videoAriaLabel: 'Digital signage totem showcase', cards: [
    { title: 'Centralized Management', text: 'Control every display from one secure cloud dashboard.' }, { title: 'Instant Content Updates', text: 'Publish new content to every screen within minutes.' },
    { title: 'Simple Monthly Pricing', text: 'Affordable subscription plans with pricing per display.' }, { title: 'Works With Your Screens', text: 'Use your existing TVs and displays, no specialized hardware required.' },
  ] },
  neoSlide: { label: 'MEET NEOSLIDE', heading: 'Digital signage, without the complexity.', copy: 'NeoSlide brings your screens, content and schedules together in one easy-to-manage platform. From a single display to an entire network, you can publish, update and control what appears on every screen wherever they are.' },
  howItWorks: { label: 'HOW IT WORKS', heading: 'One platform. Every screen.', copy: 'Create, organize and schedule content from the NeoSlide dashboard, then assign it to individual screens or display groups. From standard displays and digital totems to video walls and large-format installations, every connected screen stays managed from one place.', visualAriaLabel: 'Digital signage workflow illustration', illustrationAriaLabel: 'NeoSlide digital signage management workflow illustration' },
  dashboard: { ariaLabel: 'Digital signage dashboard section', label: 'Dashboard', heading: 'Manage every display from one intuitive dashboard.', copy: 'Neoslide offers flexible content management, allowing you to update and control your displays from anywhere using just a web browser and an internet connection. Access the platform 24/7 from a smartphone, tablet, or laptop, and publish changes with confidence. Every update is automatically synchronized across all connected screens, ensuring new content goes live in just a few minutes.', laptopAriaLabel: 'Laptop opening mockup', playAriaLabel: 'Play dashboard explainer video', previewAlt: 'Preview of the Neoslide admin dashboard video', playLabel: 'Play video', videoAriaLabel: 'Dashboard explainer video' },
  realtime: { ariaLabel: 'Real-time content section', label: 'Real-Time Content', heading: 'Turn live data into engaging digital experiences.', copy: 'Display real-time information effortlessly with digital signage that presents live generated data. Keep your audience engaged and up-to-date with dynamic content that is updated automatically.', imageAlt: 'Real-time digital signage weather content' },
  industries: { label: 'Industry Solutions', heading: 'Digital signage that adapts to your business.', copy: 'Every industry communicates differently. Neoslide provides flexible digital signage solutions that help you deliver the right information, to the right audience, at the right time.', cta: 'Explore case studies', metricsAriaLabel: 'Industry solution impact metrics', listAriaLabel: 'Industry solutions details' },
  displayTypes: { label: 'Flexible Deployment', heading: 'Built for the displays you use.', copy: 'NeoSlide brings standard screens, digital totems, menu boards, interactive kiosks and large-format installations into one centrally managed network. Start with new hardware or connect compatible displays you already own.', gridAriaLabel: 'NeoSlide display deployment options', tagsSuffix: 'display tags', items: [
    { counter: '01', title: 'Standard Displays', description: 'Run promotional, informational and branded content on landscape or portrait commercial screens.', badge: 'Landscape · Portrait · Indoor', imageAlt: 'Commercial standard displays arranged in landscape and portrait orientations' },
    { counter: '02', title: 'Digital Totems', description: 'Manage freestanding displays across entrances, showrooms, retail spaces and public areas.', badge: 'Freestanding · Single or double-sided', imageAlt: 'Slim freestanding digital totem display for public spaces' },
    { counter: '03', title: 'Menu Boards', description: 'Keep menus, pricing and promotions consistent across coordinated multi-screen layouts.', badge: 'Multi-screen · Scheduled updates', imageAlt: 'Coordinated digital menu board displays arranged side by side' },
    { counter: '04', title: 'Interactive Kiosks', description: 'Create touch-enabled experiences for self-service, product browsing, directories and wayfinding.', badge: 'Touchscreen · Self-service · Wayfinding', imageAlt: 'Interactive touchscreen kiosk for self-service and wayfinding' },
    { counter: '05', title: 'Video Walls & Large Format', description: 'Deliver coordinated content across video walls, ultra-wide screens and large-format installations.', badge: 'Video walls · Ultra-wide · LED', imageAlt: 'Large-format video wall and ultra-wide display arrangement' },
    { counter: '06', title: 'Your Existing Displays', description: 'Already have screens installed? Connect compatible displays and media players to NeoSlide and manage them alongside new installations.', badge: 'Compatible displays · Media players', imageAlt: 'Mixed display formats connected under a single management system' },
  ] },
  anyScreen: { label: 'Any Screen. Any Size.', heading: 'Your content, wherever it belongs.', paragraphs: ['Neoslide digital signage platform provides a highly flexible and adaptable approach to displaying content across different screens. Regardless of the type or brand of screen being used, the platform has no limitations and can seamlessly adapt to the requirements of each display.', 'The platform is designed to work across a wide range of devices, from portrait and landscape screens to large-scale video walls, ensuring that users have access to content on any screen that they prefer to use.'] },
  demoService: 'Digital Signage',
} as const;
export type DigitalSignageContent = typeof englishDigitalSignageContent;
export const digitalSignageContent: Localized<DigitalSignageContent> = { en: englishDigitalSignageContent, mk: englishDigitalSignageContent };
