import type { Localized } from '../types';
import { shelfLabelsPerformanceStats } from './data/shelfLabelsPerformanceStats';
import { shelfLabelHardwareFeatures } from './data/shelfLabelHardwareFeatures';
import { shelfLabelScrollFeatures } from './data/shelfLabelScrollFeatures';
export const englishShelfLabelsContent = {
 seo:{title:'Electronic Shelf Labels | BlackBox Solutions',description:'Transform retail pricing operations with cloud-connected electronic shelf labels that sync pricing, promotions, and product details across every store.'},
 viewer:{ariaLabel:'Interactive 3D shelf label model',loadingLabel:'Loading model…'},
 hero:{ariaLabel:'Shelf labels hero',headlineStart:'Transform your retail with ',highlights:['smarter','pricing.'],lead:'Replace traditional paper labels with cloud-connected electronic shelf labels that instantly synchronize pricing, promotions, and product information across every store.'},
 howItWorks:{label:'HOW IT WORKS',heading:'One update. Everywhere. Instantly. Manage every shelf from a single platform.',copy:'Change a price once in your existing POS or ERP system, and every connected Electronic Shelf Label updates automatically through a secure wireless network. No manual replacements, no pricing inconsistencies, and no wasted staff time.',visualAriaLabel:'Shelf label synchronization illustration',illustrationAriaLabel:'Electronic shelf label synchronization workflow illustration'},
 performance:{label:'Proven Performance',heading:'Why Retailers Choose Electronic Shelf Labels',copy:'Automate repetitive tasks, eliminate pricing inconsistencies, and manage thousands of labels from a single platform, all while improving the shopping experience for your customers.',ariaLabel:'Shelf labels performance metrics',stats:shelfLabelsPerformanceStats},
 overview:{label:'Product Overview',heading:'Engineered for large-scale deployments.',copy:'Designed for retailers that require dependable, low-maintenance hardware, our Electronic Shelf Labels combine ultra-low-power e-ink technology, secure wireless communication, extended battery life, and durable construction into a single platform. Flexible display options, configurable housing, and reliable operation across a wide temperature range make them suitable for supermarkets, pharmacies, electronics stores, and other demanding retail environments.',colorAriaLabel:'Product color',colors:['Black','White','Wood']},
 hardware:{label:'Hardware Details',heading:'Purpose-built hardware for every retail environment.',copy:'Designed for reliability, efficiency, and long-term performance, our Electronic Shelf Labels combine ultra-low power consumption with crisp displays and durable construction, making them ideal for everything from supermarkets to refrigerated storage.',ariaLabel:'Electronic shelf label hardware features',features:shelfLabelHardwareFeatures},
 features:{ariaLabel:'Shelf labels feature highlights',label:'Core Capabilities',heading:'Powerful features for modern retail operations.',copy:'Take full control of your Electronic Shelf Labels with a centralized platform designed for real-time updates, remote management, and seamless integration with your existing retail systems.',listAriaLabel:'Product features list',illustrationAriaLabel:'Shelf label layer illustration',layers:['Bottom layer','PCB layer','TFT matrix layer','Micro capsules layer','Color filter layer','Touch panel layer','Front light layer','Top shelf label layer'],items:shelfLabelScrollFeatures},
 demoService:'Electronic Shelf Labels'
} as const;
export type ShelfLabelsContent=typeof englishShelfLabelsContent;
export const shelfLabelsContent:Localized<ShelfLabelsContent>={en:englishShelfLabelsContent,mk:englishShelfLabelsContent};
