import type{Localized}from'../types';
export const englishVideoStreamingContent={
 seo:{title:'Video Streaming Solutions | BlackBox Solutions',description:'Secure, scalable video streaming solutions for live broadcasts, VOD platforms, and custom business media delivery.'},
 hero:{ariaLabel:'Video streaming intro',titleStart:'Powering ',highlightOne:'next-generation ',highlightTwo:'streaming',titleEnd:' experiences.',lead:'Deliver secure, scalable, and high-performance streaming experiences for businesses, hospitality, education, and media. From live broadcasts and video-on-demand platforms to custom in-room entertainment systems, we build solutions that deliver content reliably across every device.',cta:'Find out more',nextLabel:'NEXT-GEN STREAMING',nextHeading:'Built for every screen. Engineered for scale.',nextCopy:'Behind every seamless viewing experience is a reliable OTT platform. We build scalable streaming solutions that support Live, VoD, DVR, Smart TVs, browsers, mobile devices, and hospitality systems. Every solution is designed for reliable performance, secure delivery, and effortless growth.'},
 consulting:{label:'STRATEGY & OPTIMIZATION',heading:'Expert guidance from planning to deployment.',copy:'Stop guessing with your streaming infrastructure. We consult on custom pipeline design, low-latency protocols, and CDN optimization so you can launch massive-scale live events with zero downtime.',ariaLabel:'Video streaming consulting capabilities',highlightsSuffix:'highlights',cards:[
 {title:'Strategy',copy:'Planning every streaming platform around your business goals and long-term growth.',points:['Platform architecture','Technology selection','Scalability planning'],video:'/videos/video-streaming/recording.mp4'},
 {title:'Infrastructure',copy:'Building a resilient streaming backbone optimized for performance and reliability.',points:['CDN optimization','Encoding workflows','Low-latency protocols'],video:'/videos/video-streaming/network.mp4'},
 {title:'Global Delivery',copy:'Delivering consistent, high-quality streaming experiences anywhere in the world.',points:['Multi-region deployment','Worldwide delivery','High availability'],video:'/videos/video-streaming/global.mp4'}]},
 hotel:{label:'Smart Hospitality Platforms',heading:'Entertainment that goes beyond the television.',copy:'Bring your guest rooms into the digital age. Our interactive hotel platform seamlessly integrates with PMS systems to deliver personalized content, custom branding, and real-time interactive guest services to every screen.',interfaceAriaLabel:'Interactive hospitality interface demo',featuredAriaLabel:'Hospitality platform featured visualization',featuredAlt:'Hospitality platform featured visualization'},
 bento:{services:['Room Service','Concierge','Front Desk','Restaurant','Spa & Wellness','Pool Access','Fitness Center','Fast Checkout','Taxi Service'],travelMeta:['Tomorrow','08:45','Gate A12'],controls:['Lights','Lock','AC','Music','DND','Shades'],discoverLabel:'Discover More',alertCopy:'Late checkout available until 2 PM',resumeLabel:'Resume watching',dashboardAriaLabel:'Interactive hotel platform preview dashboard',localTimeAriaLabel:'Local Skopje time',localTime:'Local Time',zone:'Europe/Skopje',travelAriaLabel:'Travel and arrival information',travel:'Travel',flight:'Flight LH1428',travelDetails:'Travel details',roomControlsAriaLabel:'Room controls',roomControls:'Room Controls',switchesAriaLabel:'Room control switches',hotelServicesAriaLabel:'Hotel services',hotelServices:'Hotel Services',attractionsAriaLabel:'Local attractions',attractions:'Local Attractions',discoverMore:'Discover more local attractions',notificationsAriaLabel:'Notifications',notifications:'Notifications',newMessage:'1 New Message',playingAriaLabel:'Currently playing content',playing:'Currently Playing',program:'Nature Documentary',resume:'Resume watching',statusAriaLabel:'Connection and room status',wifi:'Wi-Fi Connected',guest:'BlackBox_Guest_514',room:'Room 1208'},
 demoService:'Video Streaming'
}as const; export type VideoStreamingContent=typeof englishVideoStreamingContent; export const videoStreamingContent:Localized<VideoStreamingContent>={en:englishVideoStreamingContent,mk:englishVideoStreamingContent};
